### PR TITLE
Add iossimulator-arm64 build

### PR DESCRIPTION
**Pull request by filipnavara**
Note that this splits the build to produce two `e_sqlite3.a` files as well, so if there's any dependency on the folder structure in SQLitePCL.raw it will need to be updated.

### CODE REVIEW

**Comment by filipnavara** [comment]
@ericsink Can I get your attention on this one? [.NET Meteor](https://github.com/JaneySprings/DotNet.Meteor) recently started doing `iossimulator-arm64` build by default and I would like this to work out of the box when SQLite is used.

**Comment by ericsink** [comment]
@filipnavara My apologies for the delay. I have done a poor job lately keeping up with things. :-( Anyway, I have merged this PR, and I will fix the paths in SQLitePCLRaw.

**Comment by filipnavara** [comment]
> My apologies for the delay.

No problem. I didn't want to bother while you were at MVP summit / recovering.

**Comment by ericsink** [comment]
@filipnavara I'm having a bit of trouble figuring out how to update the SQLitePCLRaw side, and the easiest/laziest thing to do is ask you.

This is where the `e_sqlite3.a` file is embedded into an assembly:

https://github.com/ericsink/SQLitePCL.raw/blob/ab7bcc13d1f3c36e6a9109cbf68573c4edfd8820/src/SQLitePCLRaw.lib.e_sqlite3.ios/SQLitePCLRaw.lib.e_sqlite3.ios.csproj#L16-L18

But now that `e_sqlite3.a` is split into device and simulator versions, what should that look like?  I assume I need to have conditions based on the RID.  Do I need to create two versions of that assembly, one for simulator and one for device?

It has apparently been quite a while since I had to deal with ios simulator issues, and I have forgotten, or stuff has changed, or both.  :-(

Thanks.

**Comment by filipnavara** [comment]
I was originally expecting to just slap a `LinkTarget` into the `LinkWith` attribute constructor but apparently that's not possible because `x86_64 = Simulator64` in the `LinkTarget` enum. So next thing I will check is RID-specific packages. Another thing that may be viable is to simply link against the dynamic libraries on the simulator, it doesn't need a static library (unlike the device).

**Comment by ericsink** [comment]
And for clarity:  Would it still be possible to go back to just one `.a` file?  Was that change required, or merely preferable for some reason?

**Comment by filipnavara** [comment]
> And for clarity: Would it still be possible to go back to just one `.a` file? Was that change required, or merely preferable for some reason?

It's impossible to have two arm64 targets (ios-arm64 / iossimulator-arm64) within a single `.a` file. It's also [officially discouraged](https://developer.apple.com/forums/thread/673387) to mix simulator and device builds within single `.a` file.

The viable approach seems to be to do what https://www.nuget.org/packages/Esri.ArcGISRuntime.runtimes.iOS/ does:
- Include both .a files in the NuGet
- Don't use `LinkWith` attribute and `.a` embedded as a resource
- Add `build\{tfm}\{package}.targets` and `buildTransitive\{tfm}\{package}.targets` scripts that include `<NativeLibrary>` ItemGroup defined based on the RID.

The general approach is relatively easy to replicate. The tricky part is to ensure that it works on the legacy TFMs (xamarin.ios).

**Comment by ericsink** [comment]
I saw your twitter thread with Morten.  I'll take a look at how they've got things setup and try to follow that example.

**Pull request merged**
