### PR TITLE
Add sqlite3mc and e_sqlite3mc to build process

### PR DESCRIPTION
**Pull request by utelle**
Integrate SQLite3 Multiple Ciphers into SQLitePCLraw

- Add source files in directory sqlite3mc
- Add functions to generate build files for sqlite3mc and e_sqlite3mc to bld/cb.cs
- Adjust GitHub workflow
- Adjust README.md

### CODE REVIEW

**Comment by bricelam** [comment]
I'm just using the binaries for `sqlite3mc` in https://github.com/ericsink/SQLitePCL.raw/pull/563. Is there a difference between them an e_sqlite3mc?

**Comment by utelle** [comment]
> I'm just using the binaries for `sqlite3mc` in [ericsink/SQLitePCL.raw#563](https://github.com/ericsink/SQLitePCL.raw/pull/563). Is there a difference between them and e_sqlite3mc?

Except for the name there is no difference. 

The build files coming with SQLite3 Multiple Ciphers use the library name sqlite3mc. Therefore it may be better to use the name e_sqlite3mc in the .NET packages to avoid potential name clashes, if users install both.

**Comment by ericsink** [comment]
I am always a bit amazed when someone else works on `cb.cs`.  It is not a thing of beauty.

**Comment by utelle** [comment]
> I am always a bit amazed when someone else works on `cb.cs`. It is not a thing of beauty.

I have to admit that I chose a somewhat "quick&dirty" approach to make the code "work". IMHO the code should be cleaned up a bit, as soon as we have decided, which library name will be used for the NuGet packages - `sqlite3mc` or `e_sqlite3mc`.

Actually, I used a copy of the function `write_e_sqlite3()` as a template for `write_e_sqlite3mc()` and `write_sqlite3mc()` .
Most likely the `#if not ... #endif` sections can be removed. Regarding white space either blanks or tabs should be used, not a mixture.

**Pull request merged**
