### PR TITLE
Support mips64 architecture on Linux platform

### PR DESCRIPTION
**Pull request by sunny868**

### CODE REVIEW

**Comment by sunny868** [comment]
libtomcrypt version follow README_libtomcrypt.txt

**Comment by ericsink** [comment]
So I see you have included the .so files.  Does that mean this build worked for you?

What platform did you do the build on?  Ubuntu?  Which version?

If Ubuntu, which package did you install for the cross compiler?

**Comment by sunny868** [comment]
Ubuntu 16.04 .
cross compiler is  gcc-mips64el-linux-gnuabi64 (gcc version 5.4.0 ),you can install it use "apt-get install gcc-mips64el-linux-gnuabi64"

By the way. Now,Our team has supported .NET core on MIPS64 architecture,https://github.com/gsvm/coreclr
so I want this PR can be merged . Thank you very much.

**Comment by ericsink** [comment]
Your build script changes and the cross-compiler package you mentioned seem to be working fine for me.  Thanks!

**Pull request merged**
